name: Build Tests

on:
  push:
    paths-ignore:
      - "*.md"
      - "*.dbc"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Cache Nix
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cache/nix
      #     key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
      #     restore-keys: |
      #       nix-${{ runner.os }}-

      # - name: Install Nix Action
      #   uses: cachix/install-nix-action@v31

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clean & Build tests
        working-directory: Firmware
        run: |
          make clean
          # cd Tests/
          # python3 makeAllTests.py

      # - name: Clean Root
      #   working-directory: Firmware
      #   run: make clean

